import sys

from graph import app
import constants
from colorama import Fore, Style, init
from config.custom_printer import Custom_printer

init(autoreset=True)
printer = Custom_printer()


def banner():
    print(f"\n" * 1)
    printer.cout_cyan("=" * 60)
    printer.cout_cyan("INVESTMENT EXPERT")
    printer.cout_cyan("=" * 60)
    print("\n")
    printer.cout_red("DISCLAIMER: This output is generated by an AI assistant. Please verify the information before taking any action. " \
    "\nBy using the system you agree to our T&C.")
    print("\n")
    printer.cout_yellow("Welcome, you can ask questions about investment guidance & financial advice about stock market of USA.")
    printer.cout_yellow("Type 'exit' or 'quit' to stop")

if __name__ == "__main__":
    banner()

    conversation_hist = []

    you = "👤 You:"
    agent = "🤖 Agent:"

    print("\n" * 1)
    print()

    printer.cout_magenta(f"{agent} Hi I am an Investment Expert Agent. How may I help you today? \n")
    user_input = input(f"{Fore.BLUE}{you} {Style.RESET_ALL}")

    while True:

        if user_input.lower() in ['exit', 'quit', 'q']:
            print("\n")
            printer.cout_magenta(f"{agent} 👋 Thanks for using Investment Expert Agent!")
            print("\n")
            break
        
        conversation_hist.append({
            # "role": "user",
            "user_input": user_input,
        })

        print(f"\n{Fore.YELLOW}🤔 Thinking...{Style.RESET_ALL}")

        response = app.invoke({"user_input": user_input})
        conversation_hist.append({ "agent:": response[constants.AGENT_STATE_AGGREGATOR_AGENT]})

        print("\n")
        printer.cout_magenta(f"{agent} {response[constants.AGENT_STATE_AGGREGATOR_AGENT]} \n")
        
        user_input = input(f"{Fore.BLUE}{you} {Style.RESET_ALL}")


        






